services:
  api:
    build:
      context: .:app/
      dockerfile: Dockerfile
    container_name: todo-api
    ports:
      - '${PORT}:8080'
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - todo-db
    networks:
      - todo

  todo-db:
    image: postgres:15
    container_name: todo-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '${DATABASE_PORT}:5432'
    networks:
      - todo

volumes:
  pgdata:

networks:
  todo:
    name: 'todo'
